#!/bin/bash
BRANCH=`git branch --show-current`
if [ $BRANCH = "main" ]; then BRANCH="latest"; fi
docker build . -t ghcr.io/ptr33/knxd-docker:$BRANCH   && \
docker push ghcr.io/ptr33/knxd-docker:$BRANCH
